### ISSUE TITLE
Highlight discord username in the messenger message

### ISSUE THREAD

**Issue by mind12** [Bjornskjald/miscord#88]
Enhancement request:
Discord username is blurred in the message content. 
Can it be highlighted somehow (bold, italic, text coloring etc)?

Thank you.

**Comment by Bjornskjald** [comment]
@mind12 On [desktop version](https://messenger.com) it could be bold, but on mobile Messenger it would show like this: `*Username:*`

**Comment by mind12** [comment]
Ohh too bad :(
Any other options? Maybe a new line after the username?

Users are complaining that they just read through the bot's messages because they realize only the facebook username and miss the discord username in the message.

**Comment by Bjornskjald** [comment]
Well, I could implement a switch for the bold username, but I have no idea how to make username more visible.  
I think newlines would make too much empty space

**Comment by Bjornskjald** [comment]
Maybe backticks?
Desktop: ![Desktop](https://user-images.githubusercontent.com/26630168/37299896-dbd4a98a-2624-11e8-9c8d-626fc0e04464.png)
Mobile: ![Mobile](https://user-images.githubusercontent.com/26630168/37299924-f279650e-2624-11e8-9f85-01c576cb0ca5.png)

**Comment by mind12** [comment]
It's not much a difference on mobile where everybody reads the messages.

I tested this site for generating a message and a bold test message look the same on web and mobile.
How do they do that?
https://gschoppe.com/projects/fbformat/

**Comment by Bjornskjald** [comment]
I think the bold username would be the best, because it's visible on desktop and _quite_ visible on mobile.

Mobile app uses it's own parsing method for formatting, and they haven't implemented formatting text yet, only links/dates.

**Comment by mind12** [comment]
Yeah bould would be the best.
Any idea how that site generates the bold style?

**Comment by simeonlg** [comment]
I know the issue is closed, but I am not sure if its worth it opening another issue. My citys discord have been using square brackets instead of the bold usernames as it looks the same on all platforms and looks better in my opinion. 

Perhaps some other users would like a choice in the config file too. Should not be any priority to implement as somebody that can run the server probably can edit a few characters in discord.js

![image](https://user-images.githubusercontent.com/8640358/39671951-e281c876-5121-11e8-9ea2-e46638381a8c.png)

**Comment by Bjornskjald** [comment]
I discussed it already on our Discord, the best way would be to add "format" field in the config and let people use their own formats, in this case: `[{username}] {message}`
